server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:job_prep_app}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:karthik521}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone : UTC

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

  ## App Properties
app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs : 604800000

  ## Spring Profiles
  # spring.profiles.active=prod

